version: 2

project_name: sharpify

before:
  hooks:
    - go mod tidy

builds:
  - id: sharpify
    main: .
    binary: sharpify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: sharpify
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: sharpify
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/sharpify"
    description: "CLI tool to modernize legacy C# code"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/sharpify", "--version"
    install: |
      bin.install "sharpify"

nfpms:
  - id: packages
    package_name: sharpify
    vendor: Sharpify
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/sharpify"
    maintainer: "Sharpify <noreply@example.com>"
    description: "CLI tool to modernize legacy C# code"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
